// Product
export const SET_PRODUCT = "PRODUCT/SET_PRODUCT";
export const FETCH_START = "PRODUCT/FETCH_START";
export const FETCH_END = "PRODUCT/FETCH_END";
export const PRODUCT_SUCCESS = "PRODUCT/PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT/PRODUCT_FAILURE";
