// Product
export const SET_PRODUCT = "PRODUCT/SET_PRODUCT";
export const PRODUCT_FETCH_START = "PRODUCT/FETCH_START";
export const PRODUCT_FETCH_END = "PRODUCT/FETCH_END";
export const PRODUCT_SUCCESS = "PRODUCT/PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT/PRODUCT_FAILURE";

// Categories
export const SET_CATEGORIES = "CATEGORIES/SET_CATEGORIES";
export const CATEGORIES_FETCH_START = "CATEGORIES/FETCH_START";
export const CATEGORIES_FETCH_END = "CATEGORIES/FETCH_END";
export const CATEGORIES_SUCCESS = "CATEGORIES/CATEGORIES_SUCCESS";
export const CATEGORIES_FAIlURE = "CATEGORIES/CATEGORIES_SUCCESS";

// ProductInfo
export const SET_PRODUCT_INFO = "PRODUCT_INFO/SET_PRODUCT_INFO";
export const PRODUCT_INFO_FETCH_START = "PRODUCT_INFO/FETCH_START";
export const PRODUCT_INFO_FETCH_END = "PRODUCT_INFO/FETCH_END";
export const PRODUCT_INFO_SUCCESS = "PRODUCT_INFO/PRODUCT_INFO_SUCCESS";
export const PRODUCT_INFO_FAILURE = "PRODUCT_INFO/PRODUCT_INFO_FAILURE";

// Brands
export const SET_BRANDS = "BRANDS/SET_BRANDS";
export const BRANDS_FETCH_START = "BRANDS/FETCH_START";
export const BRANDS_FETCH_END = "BRANDS/FETCH_END";
export const BRANDS_SUCCESS = "BRANDS/BRANDS_SUCCESS";
export const BRANDS_FAIlURE = "BRANDS/BRANDS_SUCCESS";

// Cart
export const SET_CART = "CART/SET_CART";
export const CART_FETCH_START = "CART/FETCH_START";
export const CART_FETCH_END = "CART/FETCH_END";
export const CART_SUCCESS = "CART/CART_SUCCESS";
export const CART_FAIlURE = "CART/CART_SUCCESS";
