// Product
export const SET_PRODUCT = "PRODUCT/SET_PRODUCT";
export const PRODUCT_FETCH_START = "PRODUCT/FETCH_START";
export const PRODUCT_FETCH_END = "PRODUCT/FETCH_END";
export const PRODUCT_SUCCESS = "PRODUCT/PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT/PRODUCT_FAILURE";

// Categories
export const SET_CATEGORIES = "CATEGORIES/SET_CATEGORIES";
export const CATEGORIES_FETCH_START = "CATEGORIES/FETCH_START";
export const CATEGORIES_FETCH_END = "CATEGORIES/FETCH_END";
export const CATEGORIES_SUCCESS = "CATEGORIES/CATEGORIES_SUCCESS";
export const CATEGORIES_FAIlURE = "CATEGORIES/CATEGORIES_SUCCESS";

// ProductInfo
export const SET_PRODUCT_INFO = "PRODUCT_INFO/SET_PRODUCT_INFO";
export const PRODUCT_INFO_FETCH_START = "PRODUCT_INFO/FETCH_START";
export const PRODUCT_INFO_FETCH_END = "PRODUCT_INFO/FETCH_END";
export const PRODUCT_INFO_SUCCESS = "PRODUCT_INFO/PRODUCT_INFO_SUCCESS";
export const PRODUCT_INFO_FAILURE = "PRODUCT_INFO/PRODUCT_INFO_FAILURE";
